### ISSUE TITLE
Underscores inserted in enum name with mixed lowercase and numbers

### ISSUE THREAD

**Issue by zhaakhi** [morimekta/providence#47]
Given an enum definition like

```thrift
enum Format {
    mp3 = 1;
    m4a = 2;
}
```

the enum names in Java will be "MP_3" and "M_4A"

Expected result was "MP3" and "M4A".
If the definition is uppercased this works as expected.

This may be a regression introduced when fixing https://github.com/morimekta/providence/issues/46

**Comment by morimekta** [comment]
Fixed, now with much more tests.
