### ISSUE TITLE
modified flag for _Builder.

### ISSUE THREAD

**Issue by Scrier** [morimekta/providence#51]
So for each modified field (clear, set or other) a field should be set that we can check after a state.

This means if you mutate an object and reset a field, you will have that field set as modified, and everything else is the same. 

This will help when you wan't to update fields to a database or similar to see what has been modified since you delivered it. 

This information should be _Builder unique, so if you do build().mutate(), all fields will be not modified.

**Comment by morimekta** [comment]
in release 0.3.14
