### ISSUE TITLE
Data mismatch in   HazelcastVersion4Test.testVerison4OptionalMapFieldsAll:365 

### ISSUE THREAD

**Issue by morimekta** [morimekta/providence#65]
Expected: is <hazelcastv4.OptionalMapFields{booleanValue:{false:true,true:false},shortValue:{3491:20860,26660:7282,24598:25845,9624:11131,28905:29610,15643:29359,5869:2038},longValue:{-2052012299357932477:5244134433956536352,5503294085196354516:-3992764049760542441,-8878576351568393350:3159620737860764329},doubleValue:{0.008841132659420436:0.003377461201770071,0.9444206044901979:0.9915119406312122,0.22539808384468663:0.8332091428951193,0.5250912605624628:0.013067874084439102},binaryValue:{[IqDf3/BnXmAHwDLE/qRPR/WwZHRIGalQ7v1J1VBhrKNUMF4DFmyPpZdtGEx7aDaYa8xE2GwhiMyAntjqgCdN0te5IZU3eOSnJOWkK/slUGjV/I8RkKlCT8Q]:[z2hpNgYJhzJMz+f1YnujfY+bbG6bS2EoX7pZ965kTkp1/3s],[]:[I0BHGaz6//KqlIoRsSs],[hD9/hRTXzULfWcOHX5PnANn+FAANOQuDNsRL0Wlj4BiVbYdcm7E]:[Vuytw+rMPFPNh+46Pr7JS7ZCLZkuTNcMLhMU/OKs3mI],[zpi4+jdNRw5Lq1XTaza4D7FJLLgq62HyjKKPQ7Tid6qhdex7jxEsRGPHk2T52csGEiQNWw]:[SqR5fKmvGkSAitEE2h6VtvUzzZ8CFByV9xuyiFROxYATOFhyVeQ+yS/A1zRmfFP3Pw3dW9nN5rAACl4G2WX9Wm/jaA60kOlSyMIqFkXP/59YcbL2jTk98mpmR/jD6ks4EPolKF7gV8eZ24dy5uTAePWI],[QVRsYYGutgVsuPi1TwaHCs+pI/rNWTktqCdt73ED0WytRGl/yPE]:[aoXvi2xF5Z3eRtx6QMqOWA4mfCzU9MrCjPKp8Pr+Xgys+a1SuZ2qqP0qeCdfaCH0/8OhJlA],[uq+pMO/9biZFF9hWwPUacuO1dgU]:[C9HAog],[LGPXzYjb7V3q10cEcEmTh0XJirS1VE1KnqOK1XtAYdIgEBGuIauBTxcUPfQJbQPf4jhrku3JzO32h5ksCgDKFYrYPUampZ/O4IiQxL5MpvNSUyvW3F2R84EPnc9nVlecW+oLdfFjrhvUg8o]:[3+DLlSCxL+oU69Ksd7OXYfaPwA4ATqiTpKcbCsuw6FVjQnHgpqMpMPNjSO71EK47ikGXFspu9KGAh1Hvq9qJ6e6GZ6CjFjL5wxgEnJAaDacr03nX0KroQzmvLwO47TWFKcCVlHs],[iH/mvjK7khWg/eP0rTZlQKkzVyMrpl9ARYk4zLMcBQncQj/1NlXOHbh02BepoATwL8NrFVVqpsHL6OvTL734s4oplyhBZvhnsVID1F8DhTjLuAORwlLpKMFhRilCvwspMj8rJ0E+3s96nW4]:[azBlL45CAvi7z0loJDwEwynVOR10TsdjOv5+nvkqUQfuJxwYXJMYcRdsXjeqRNlFt4Ej82GDG5IN9nYc0vCQ5UQwpTWwGaq11IfoVspmi58e],[AMbivZtcq1HG18bPbYQ3WloXF5M34VNTg/84pQeaNUtyPjHBWuYkFj4XCMWioSdX52WA]:[x2V4YIJg91nbxkAPnJQP7cbsbfGUprPBoCPI/XBcAQ9d7KCOlsmX/Oa7FkikGCw5Jf8Qhq+cfmOBduI7],[m6Am8lFWu71qhdCyxJ6U4QWBRCLruf/fKmTVqKZbQ6Z0ipxud7anAaqbrJtQupMa85NrywoOTGXlTi4SMbUxgpo3]:[9usPdwasEqqV1pPRjYDSKge8B/Drv5M]},valueValue:{FOURTH:ELEVENTH,FIFTEENTH:SIXTH,THIRTEENTH:TWENTIETH},compactValue:{{name:"utrbpsafysnwalwqlhipffkwbfqmlvwwzgjxwfnbu"id:286838769,label:"xcmbonuqjswnrojykssbtpeygkjkuqktiaytfvknuzr"}:{name:"uymrjhupgegxinhp"id:2061232318,label:"jxxznvalgrq"},{name:"uhtsujajkedzvxddfpczbcixjlc"id:546885867,label:"neqnxqfrlykwjixkzzhxlznxhgzkxziwzrntevphdkmquatngmqcpqcqekcptvmmbtdpgeutugrnuxvofkyjtplcfzr"}:{name:"dacgfstgfjczhcabbzmkpazfbydxbniwzvcpt"id:-1946573160,label:"shlygrtksltv"},{name:"tmqwwuglupuvojatnyepgczmvlegqayglizysiyjvrormvmwvuzwifpghavaeilpbsikqwr"id:-266495549,label:"ausnmyxrwtrugzxqimzrquwybfrxgeqrlihmbvpdngldkuwkxwmcyryobhhdrjqywpgobrpidwidongjgshhecayxzdq"}:{name:"zrrqikyjyz"id:-867954550,label:"udvrbypfmquunnwzdyjutmqquzwgpbmwoxqgpyewnwvemwzbvjmtavxwhgiexndurlxuskhuvgkprzdsjesvoqh"},{name:"igtpurejrpc"id:1881560413,label:"tfgendjqzdawtoswgzymqtobvbggwcxnexwgfgscpoteraebwrwtcpgekvstpuycnx"}:{name:"hojdblrhcioicghntnhvtccdkjruiirelurvlylnonzuphzxampoyudkbrrixylzviaamvflrdzikqnyipalszeflnbyvggpqrgfbc"id:-949760042,label:"nwenldcebcvapspxzkwbesc"},{name:"xmlw"id:-772136312,label:"xrotvovpjrytbnpntsrwrslltvrnhzhlpwmhhoyqeqleoelytmhkejwjtzfkhtypecczdczbxvnvnhdpvbbwtawlpyswahftzzzsgrsxvtqtcqzc"}:{name:"regfvznzweivjrcldocijcmmqcewoceknadtuuvfwupqgbuihxweulkbpnaiqntzpvxxxpndsrcuxdfhhfholxkwrevcfdhqvro"id:-799681602,label:"toxosymfnggjihywtikithllxshmtrzywwwhnofymceosc"},{name:"aoexphgqmjpamzwgfizyxktkqjgyjmivrokffltrnjrkgvoefsjgyfuxnreugkuuv"id:1105100587,label:"ytytfvbpidrkisbxepndcvriocjkyvwwqsvcnrkkgdlkkcjqifhzcngbxnwrujqxuriwurpwotpbeukqeesxryrccoustqvkzkpkpokljmqexqvzjkfwskptblbad"}:{name:"cxjgxnzncemnzbgkghurzvlszxo"id:-1619525847,label:"mwgpsbgixumobamewldyozhbwzyhahbxbqwakmkwhn"},{name:"qvwtzhkkqmootfykw"id:-377666801,label:"bxcsuhyemfitjcojxqvqgftpcpkugpiivwjqzjorvfwovpszvnmxrhsvmyujhvyrlkjwiffjnkhsupizwukyohjwqp"}:{name:"kpxfwhretchgnvzfdqknusdfoibkpfddkgliccwmdzszyntaprasqopbnmbvynoipsxataxqnpmulqxmohkqzatqblwmwjnqtyatfxcgrmxlgl"id:675556868,label:"gxymppubfejdusawtvjzkocjxlekzehfmvqol"},{name:"lmwriljdgkwrtwgkxbcqf"id:1619874426,label:"pfllleopymkqhsyewlyjlwhewngbodkewerziuhshmnjnrrztvkbnpogpbslkgmnsuellbaevydcgaephpbrtasqxhmngkfahfasjefvcxtifvwdgxxgjypblhito"}:{name:"ud"id:1912311040,label:"eenqlvjjykmgnrssxyzjalavxvuxdreqsoezdrfoptcjmscupmmitlvgybxvjqyfypiizimcjutwewotaxhksdwunddoyylisnovztmxlxvwcxo"},{name:"zksgxsxdthcuzbtrkrpxmeaaikwzwwsezbynqkruotpasaicndykcdccavgkttdslizuboaeexjvt"id:-1735084020,label:"wfcnqtunukoxritirwrvysydkavrajwoduavuissqevostgohzkxkwtphnhzutxyfcgomgruzdbforrijatzdbospxxajfhlxvuaternoyavxsxdwtwzh"}:{name:"wizqcahqxvjhvfadxvytagikcemmaiesudgwxjcihbubqihsjbwx"id:-1737400598,label:"gpdfqvsedtnozwitvofomvobnuflsvkysxxyakfvaslnecotxyyuylarnawikhcafsquxfujgyggjxlcxwqylqvpuieatlcoajmxbdtcd"},{name:"sbnwjpbbapxxipliosmyteczxytoecklpipjpxydrgrudenumfpbwuujtavzqaoxu"id:-809422755,label:"lavelcxtzmhetdzddixyazjgwyqnbpzjmsfraxpleuxbenkf"}:{name:"issffsznooiclyeyjpxoijwiwnnieaqexruampzuszgzzzgoejbvcdnkeyhunahnwvsbxmdxkyoq"id:75636853,label:"fppjefuizjtuzsoktesglqmtqhcxcluegvxccikawpp"}},anotherStringValue:{"sdeefyjvyadcilufwleacxxrqtcxcndxbiecfrpxrrldppykcrfssainawhsuqrihyoaoogjogvjyiokgicrncmxvsebprhevcd":"qochtqdv","klmwnoghnrwqkhlimclggwihzrxlkrvfzplndcfuvhcgbsrtbzrcgkhqruxppblleddbxzxnvzzphequujaqrtbqusrapsnisgchxxskinapbbjqrexf":"camcbhyujdtmaikccmmmnxsqlzeitzygkpragzqquwedpsvtxnyfeaqkzqykjpnsggopxktaxuzjjjiyogueqedyspodlkwmcgufirptqpgivojnydhig","dnocjdbdfvesnlslifucfucaugewvrbbvkqackqhdpfulme":"vcpmxwdwkbkofhmaxqipgztebubcfdbldvoshawxbtngcpnvaohefhnfzukfkhmxmplotjtuwvybxvbrkqcnqkgdpoqouqhigjaizndtxaxtgprdfqjvhcvjivnj","dmjyohoiovkjnudejixxpeftosdzwufmkmcgiowhqiydvgxzsdarkspswadlwlylbbfbhmcaywbjozlntbjfvhfpcon":"ymfzfeuaxezjhawkoobxmhxmzxpccsudnodceydrzqaoswdznjbwoxooaknwavdsdwilwbxtiwmqzrowklezitluhmvtco","yziockgtcfqwyosmgekkuzqyyoubhyhtpqcyrtjnvonnywwaznbhscxlncywrpudsnbmpvexpmd":"ilhgdwzoswvixkrjqioziztblczmzvhzjwrfdivizktdfronoffkjvoiytgdzrealcbr","flswbjyxychdodglfuhtmbhyimychdwwdzdbashkvzyrtdbyuejsvctlsiypgvpofmlceriqubgwcmwwxvaalgchbiuimd":"ulbfjesqxlpyyixskycyqbftrobgovqfdvwhygaihrbfrzubgmsblyxflgvodaneekarzitlniuztfgyyqrhgybbbmldjlmslbdy","fmgnnackmzabrstpfzowiqhsmbtnctyhgwtgbamnfnatkbrutewtflseydogfuuygwuwdmhhozdsd":"uaahdtzkqumeebmswkfbdltzssbilbzgofbtiuqvntvx","epvfkge":"qvvpswqnvrbkqdwpaumuayeytjldqseugdsgtflonq","adptuowtzghpukwiostxpbyffojpyuwfowfkdzimsbqv":"chochcvdoyixwxnxxlitltgktdjafmjfviddsfdgaouoyzozxaduoiklxzldpxljgfaghewklebfkfylkdqnybdqoxptxqrpykxmggokmlqsfagwoiul","hvwtjrenqurbsharwchszyxkgwsoflzopkayancpcjpgipawdcbhldahjabhxn":"bpxbuvnwxlryzqdzbpeckyeeojugagfsqqgysubiuveffilawgsjqioppfoikxhsjkewiumfjypgxmikmkwfmvifwsrylpmjrbkhrbcvinyonesft","jywcneutrcsomtrlpfvtjcvwcymiqjnabzacibedilqfkrmsxxuwwfgkghlvmjr":"uoqmjkkbddowunbyiusvlyieydacyixtaigqtfxdfgudjtvcyucdfjhnrtsxfjvqreprjovotmfmtjmcddokqhaqqsqlyw","fmrwmcstrecqhohladerqhnfwotsgqv":"bpnnvrrubpfhxcsc","bgojnyvneilveacjfkisksiawtsnrgkttisppqjohmgafzqkbmbsokjkecrqjmncnjrtfwhekquhupu":"bt","sixcszztcdpqrpfaousfgiacozsqrvdcbakatrzcjbanqceqbmfurqjtilgwhdmxtjlzwooryoqtcrmtfdwaouycdfqgyfwzmiqqktdevjbocducbq":"prfujutfrbclwicvryfnfhdmzllzjlpjhrjmvawzkljvgjmisralenisqym","zmdkwcnjwpbwpsaogiuwuownhrrxlvuxzdpijtdugvydmzudzvilmcowykjyvnljgyaiexosxajhejijaayxuiugftfidkucwchwgeefitomonmwrundhkdykevt":"prcnbsofuaflrzbsvwqzaeplcctukzqldajewiyxlezrtouuqrkszmzalazdfvswbpkxaqtqehrnkshjxiyvvuzmbyutqdaviqsrxunopkbrrhsqdryqj","fhdleizyxhqmibblcuhcnyqdjulcjngntgyfkfgqbqsijzqfchwadaefbnkixsbqdizcb":"vxzzyltdoocaqhhhpuvdqkwsvymbnapckcasedygareyzwpfsygbl","vwifyhfgpfctudepguzyjsgrrdgffluvukjgqxakjuplgypjmtfbbjkydgznhkbavomfptjimfigvcjryoqnxkecggxhmjgdbqvpbrbgaw":"fffjsgebctfmfoecejxxherksqbmdtmtnicv","whbscutzjorefinthetfvtlaqkwkynswtegegmowpejumbxmpeazwngeqpizlwzzprmnisqecprgucxjlxawshwfdsfx":"pdsabogjbfsodchsacxdr","swciqmkgwdzdepqijlkudqmkbicxqbgvigwhggmdmvzjmytqbkorloaglnluepnqlwvmjnxknxuaenkuvtbdfmqtfhecqtgzqmdjwdf":"vi","eplquetnsca":"qbmrvhfayptjvrotfmnybxysxgjyonnpkqpxflvfjfnosqrhrkodzpkhjhgpaqvzbjqchdgpkgkljejrcinfheniaxtnwnlzcltzxlypjhbqlxptpfihqze"},anotherIntegerValue:{1213398418:960432464,-654105693:1412222013,-2009252865:1534511037,997589332:-1211753359,1889519772:-1046654345,1771296406:-299842467,619339341:1965740454,-1423080636:-398821874,1574349855:537401036,927427722:-2055246709,-1422300842:1865582664,-1355434236:-1693693678,1932366046:-352419552,1826405386:1493383765,-420361849:410948288,-989130703:438679023,1312881050:-41155717,1189906672:-1696364356,-310095782:2080066197,1625850103:-540216137}}>
     but: was <hazelcastv4.OptionalMapFields{booleanValue:{false:true,true:false},byteValue:{},shortValue:{3491:20860,26660:7282,24598:25845,9624:11131,28905:29610,15643:29359,5869:2038},longValue:{-2052012299357932477:5244134433956536352,5503294085196354516:-3992764049760542441,-8878576351568393350:3159620737860764329},doubleValue:{0.008841132659420436:0.003377461201770071,0.9444206044901979:0.9915119406312122,0.22539808384468663:0.8332091428951193,0.5250912605624628:0.013067874084439102},binaryValue:{[IqDf3/BnXmAHwDLE/qRPR/WwZHRIGalQ7v1J1VBhrKNUMF4DFmyPpZdtGEx7aDaYa8xE2GwhiMyAntjqgCdN0te5IZU3eOSnJOWkK/slUGjV/I8RkKlCT8Q]:[z2hpNgYJhzJMz+f1YnujfY+bbG6bS2EoX7pZ965kTkp1/3s],[]:[I0BHGaz6//KqlIoRsSs],[hD9/hRTXzULfWcOHX5PnANn+FAANOQuDNsRL0Wlj4BiVbYdcm7E]:[Vuytw+rMPFPNh+46Pr7JS7ZCLZkuTNcMLhMU/OKs3mI],[zpi4+jdNRw5Lq1XTaza4D7FJLLgq62HyjKKPQ7Tid6qhdex7jxEsRGPHk2T52csGEiQNWw]:[SqR5fKmvGkSAitEE2h6VtvUzzZ8CFByV9xuyiFROxYATOFhyVeQ+yS/A1zRmfFP3Pw3dW9nN5rAACl4G2WX9Wm/jaA60kOlSyMIqFkXP/59YcbL2jTk98mpmR/jD6ks4EPolKF7gV8eZ24dy5uTAePWI],[QVRsYYGutgVsuPi1TwaHCs+pI/rNWTktqCdt73ED0WytRGl/yPE]:[aoXvi2xF5Z3eRtx6QMqOWA4mfCzU9MrCjPKp8Pr+Xgys+a1SuZ2qqP0qeCdfaCH0/8OhJlA],[uq+pMO/9biZFF9hWwPUacuO1dgU]:[C9HAog],[LGPXzYjb7V3q10cEcEmTh0XJirS1VE1KnqOK1XtAYdIgEBGuIauBTxcUPfQJbQPf4jhrku3JzO32h5ksCgDKFYrYPUampZ/O4IiQxL5MpvNSUyvW3F2R84EPnc9nVlecW+oLdfFjrhvUg8o]:[3+DLlSCxL+oU69Ksd7OXYfaPwA4ATqiTpKcbCsuw6FVjQnHgpqMpMPNjSO71EK47ikGXFspu9KGAh1Hvq9qJ6e6GZ6CjFjL5wxgEnJAaDacr03nX0KroQzmvLwO47TWFKcCVlHs],[iH/mvjK7khWg/eP0rTZlQKkzVyMrpl9ARYk4zLMcBQncQj/1NlXOHbh02BepoATwL8NrFVVqpsHL6OvTL734s4oplyhBZvhnsVID1F8DhTjLuAORwlLpKMFhRilCvwspMj8rJ0E+3s96nW4]:[azBlL45CAvi7z0loJDwEwynVOR10TsdjOv5+nvkqUQfuJxwYXJMYcRdsXjeqRNlFt4Ej82GDG5IN9nYc0vCQ5UQwpTWwGaq11IfoVspmi58e],[AMbivZtcq1HG18bPbYQ3WloXF5M34VNTg/84pQeaNUtyPjHBWuYkFj4XCMWioSdX52WA]:[x2V4YIJg91nbxkAPnJQP7cbsbfGUprPBoCPI/XBcAQ9d7KCOlsmX/Oa7FkikGCw5Jf8Qhq+cfmOBduI7],[m6Am8lFWu71qhdCyxJ6U4QWBRCLruf/fKmTVqKZbQ6Z0ipxud7anAaqbrJtQupMa85NrywoOTGXlTi4SMbUxgpo3]:[9usPdwasEqqV1pPRjYDSKge8B/Drv5M]},valueValue:{FOURTH:ELEVENTH,FIFTEENTH:SIXTH,THIRTEENTH:TWENTIETH},compactValue:{{name:"utrbpsafysnwalwqlhipffkwbfqmlvwwzgjxwfnbu"id:286838769,label:"xcmbonuqjswnrojykssbtpeygkjkuqktiaytfvknuzr"}:{name:"uymrjhupgegxinhp"id:2061232318,label:"jxxznvalgrq"},{name:"uhtsujajkedzvxddfpczbcixjlc"id:546885867,label:"neqnxqfrlykwjixkzzhxlznxhgzkxziwzrntevphdkmquatngmqcpqcqekcptvmmbtdpgeutugrnuxvofkyjtplcfzr"}:{name:"dacgfstgfjczhcabbzmkpazfbydxbniwzvcpt"id:-1946573160,label:"shlygrtksltv"},{name:"tmqwwuglupuvojatnyepgczmvlegqayglizysiyjvrormvmwvuzwifpghavaeilpbsikqwr"id:-266495549,label:"ausnmyxrwtrugzxqimzrquwybfrxgeqrlihmbvpdngldkuwkxwmcyryobhhdrjqywpgobrpidwidongjgshhecayxzdq"}:{name:"zrrqikyjyz"id:-867954550,label:"udvrbypfmquunnwzdyjutmqquzwgpbmwoxqgpyewnwvemwzbvjmtavxwhgiexndurlxuskhuvgkprzdsjesvoqh"},{name:"igtpurejrpc"id:1881560413,label:"tfgendjqzdawtoswgzymqtobvbggwcxnexwgfgscpoteraebwrwtcpgekvstpuycnx"}:{name:"hojdblrhcioicghntnhvtccdkjruiirelurvlylnonzuphzxampoyudkbrrixylzviaamvflrdzikqnyipalszeflnbyvggpqrgfbc"id:-949760042,label:"nwenldcebcvapspxzkwbesc"},{name:"xmlw"id:-772136312,label:"xrotvovpjrytbnpntsrwrslltvrnhzhlpwmhhoyqeqleoelytmhkejwjtzfkhtypecczdczbxvnvnhdpvbbwtawlpyswahftzzzsgrsxvtqtcqzc"}:{name:"regfvznzweivjrcldocijcmmqcewoceknadtuuvfwupqgbuihxweulkbpnaiqntzpvxxxpndsrcuxdfhhfholxkwrevcfdhqvro"id:-799681602,label:"toxosymfnggjihywtikithllxshmtrzywwwhnofymceosc"},{name:"aoexphgqmjpamzwgfizyxktkqjgyjmivrokffltrnjrkgvoefsjgyfuxnreugkuuv"id:1105100587,label:"ytytfvbpidrkisbxepndcvriocjkyvwwqsvcnrkkgdlkkcjqifhzcngbxnwrujqxuriwurpwotpbeukqeesxryrccoustqvkzkpkpokljmqexqvzjkfwskptblbad"}:{name:"cxjgxnzncemnzbgkghurzvlszxo"id:-1619525847,label:"mwgpsbgixumobamewldyozhbwzyhahbxbqwakmkwhn"},{name:"qvwtzhkkqmootfykw"id:-377666801,label:"bxcsuhyemfitjcojxqvqgftpcpkugpiivwjqzjorvfwovpszvnmxrhsvmyujhvyrlkjwiffjnkhsupizwukyohjwqp"}:{name:"kpxfwhretchgnvzfdqknusdfoibkpfddkgliccwmdzszyntaprasqopbnmbvynoipsxataxqnpmulqxmohkqzatqblwmwjnqtyatfxcgrmxlgl"id:675556868,label:"gxymppubfejdusawtvjzkocjxlekzehfmvqol"},{name:"lmwriljdgkwrtwgkxbcqf"id:1619874426,label:"pfllleopymkqhsyewlyjlwhewngbodkewerziuhshmnjnrrztvkbnpogpbslkgmnsuellbaevydcgaephpbrtasqxhmngkfahfasjefvcxtifvwdgxxgjypblhito"}:{name:"ud"id:1912311040,label:"eenqlvjjykmgnrssxyzjalavxvuxdreqsoezdrfoptcjmscupmmitlvgybxvjqyfypiizimcjutwewotaxhksdwunddoyylisnovztmxlxvwcxo"},{name:"zksgxsxdthcuzbtrkrpxmeaaikwzwwsezbynqkruotpasaicndykcdccavgkttdslizuboaeexjvt"id:-1735084020,label:"wfcnqtunukoxritirwrvysydkavrajwoduavuissqevostgohzkxkwtphnhzutxyfcgomgruzdbforrijatzdbospxxajfhlxvuaternoyavxsxdwtwzh"}:{name:"wizqcahqxvjhvfadxvytagikcemmaiesudgwxjcihbubqihsjbwx"id:-1737400598,label:"gpdfqvsedtnozwitvofomvobnuflsvkysxxyakfvaslnecotxyyuylarnawikhcafsquxfujgyggjxlcxwqylqvpuieatlcoajmxbdtcd"},{name:"sbnwjpbbapxxipliosmyteczxytoecklpipjpxydrgrudenumfpbwuujtavzqaoxu"id:-809422755,label:"lavelcxtzmhetdzddixyazjgwyqnbpzjmsfraxpleuxbenkf"}:{name:"issffsznooiclyeyjpxoijwiwnnieaqexruampzuszgzzzgoejbvcdnkeyhunahnwvsbxmdxkyoq"id:75636853,label:"fppjefuizjtuzsoktesglqmtqhcxcluegvxccikawpp"}},anotherStringValue:{"sdeefyjvyadcilufwleacxxrqtcxcndxbiecfrpxrrldppykcrfssainawhsuqrihyoaoogjogvjyiokgicrncmxvsebprhevcd":"qochtqdv","klmwnoghnrwqkhlimclggwihzrxlkrvfzplndcfuvhcgbsrtbzrcgkhqruxppblleddbxzxnvzzphequujaqrtbqusrapsnisgchxxskinapbbjqrexf":"camcbhyujdtmaikccmmmnxsqlzeitzygkpragzqquwedpsvtxnyfeaqkzqykjpnsggopxktaxuzjjjiyogueqedyspodlkwmcgufirptqpgivojnydhig","dnocjdbdfvesnlslifucfucaugewvrbbvkqackqhdpfulme":"vcpmxwdwkbkofhmaxqipgztebubcfdbldvoshawxbtngcpnvaohefhnfzukfkhmxmplotjtuwvybxvbrkqcnqkgdpoqouqhigjaizndtxaxtgprdfqjvhcvjivnj","dmjyohoiovkjnudejixxpeftosdzwufmkmcgiowhqiydvgxzsdarkspswadlwlylbbfbhmcaywbjozlntbjfvhfpcon":"ymfzfeuaxezjhawkoobxmhxmzxpccsudnodceydrzqaoswdznjbwoxooaknwavdsdwilwbxtiwmqzrowklezitluhmvtco","yziockgtcfqwyosmgekkuzqyyoubhyhtpqcyrtjnvonnywwaznbhscxlncywrpudsnbmpvexpmd":"ilhgdwzoswvixkrjqioziztblczmzvhzjwrfdivizktdfronoffkjvoiytgdzrealcbr","flswbjyxychdodglfuhtmbhyimychdwwdzdbashkvzyrtdbyuejsvctlsiypgvpofmlceriqubgwcmwwxvaalgchbiuimd":"ulbfjesqxlpyyixskycyqbftrobgovqfdvwhygaihrbfrzubgmsblyxflgvodaneekarzitlniuztfgyyqrhgybbbmldjlmslbdy","fmgnnackmzabrstpfzowiqhsmbtnctyhgwtgbamnfnatkbrutewtflseydogfuuygwuwdmhhozdsd":"uaahdtzkqumeebmswkfbdltzssbilbzgofbtiuqvntvx","epvfkge":"qvvpswqnvrbkqdwpaumuayeytjldqseugdsgtflonq","adptuowtzghpukwiostxpbyffojpyuwfowfkdzimsbqv":"chochcvdoyixwxnxxlitltgktdjafmjfviddsfdgaouoyzozxaduoiklxzldpxljgfaghewklebfkfylkdqnybdqoxptxqrpykxmggokmlqsfagwoiul","hvwtjrenqurbsharwchszyxkgwsoflzopkayancpcjpgipawdcbhldahjabhxn":"bpxbuvnwxlryzqdzbpeckyeeojugagfsqqgysubiuveffilawgsjqioppfoikxhsjkewiumfjypgxmikmkwfmvifwsrylpmjrbkhrbcvinyonesft","jywcneutrcsomtrlpfvtjcvwcymiqjnabzacibedilqfkrmsxxuwwfgkghlvmjr":"uoqmjkkbddowunbyiusvlyieydacyixtaigqtfxdfgudjtvcyucdfjhnrtsxfjvqreprjovotmfmtjmcddokqhaqqsqlyw","fmrwmcstrecqhohladerqhnfwotsgqv":"bpnnvrrubpfhxcsc","bgojnyvneilveacjfkisksiawtsnrgkttisppqjohmgafzqkbmbsokjkecrqjmncnjrtfwhekquhupu":"bt","sixcszztcdpqrpfaousfgiacozsqrvdcbakatrzcjbanqceqbmfurqjtilgwhdmxtjlzwooryoqtcrmtfdwaouycdfqgyfwzmiqqktdevjbocducbq":"prfujutfrbclwicvryfnfhdmzllzjlpjhrjmvawzkljvgjmisralenisqym","zmdkwcnjwpbwpsaogiuwuownhrrxlvuxzdpijtdugvydmzudzvilmcowykjyvnljgyaiexosxajhejijaayxuiugftfidkucwchwgeefitomonmwrundhkdykevt":"prcnbsofuaflrzbsvwqzaeplcctukzqldajewiyxlezrtouuqrkszmzalazdfvswbpkxaqtqehrnkshjxiyvvuzmbyutqdaviqsrxunopkbrrhsqdryqj","fhdleizyxhqmibblcuhcnyqdjulcjngntgyfkfgqbqsijzqfchwadaefbnkixsbqdizcb":"vxzzyltdoocaqhhhpuvdqkwsvymbnapckcasedygareyzwpfsygbl","vwifyhfgpfctudepguzyjsgrrdgffluvukjgqxakjuplgypjmtfbbjkydgznhkbavomfptjimfigvcjryoqnxkecggxhmjgdbqvpbrbgaw":"fffjsgebctfmfoecejxxherksqbmdtmtnicv","whbscutzjorefinthetfvtlaqkwkynswtegegmowpejumbxmpeazwngeqpizlwzzprmnisqecprgucxjlxawshwfdsfx":"pdsabogjbfsodchsacxdr","swciqmkgwdzdepqijlkudqmkbicxqbgvigwhggmdmvzjmytqbkorloaglnluepnqlwvmjnxknxuaenkuvtbdfmqtfhecqtgzqmdjwdf":"vi","eplquetnsca":"qbmrvhfayptjvrotfmnybxysxgjyonnpkqpxflvfjfnosqrhrkodzpkhjhgpaqvzbjqchdgpkgkljejrcinfheniaxtnwnlzcltzxlypjhbqlxptpfihqze"},anotherIntegerValue:{1213398418:960432464,-654105693:1412222013,-2009252865:1534511037,997589332:-1211753359,1889519772:-1046654345,1771296406:-299842467,619339341:1965740454,-1423080636:-398821874,1574349855:537401036,927427722:-2055246709,-1422300842:1865582664,-1355434236:-1693693678,1932366046:-352419552,1826405386:1493383765,-420361849:410948288,-989130703:438679023,1312881050:-41155717,1189906672:-1696364356,-310095782:2080066197,1625850103:-540216137}}>

**Comment by Scrier** [comment]
You don't happen to have the store on failure thing available? :)

**Comment by Scrier** [comment]
byteValue is empty collection on one and null on other.

**Comment by morimekta** [comment]
```java
            if( isSetByteValues() ) {
                portableWriter.writeByteArray("byteValues", com.google.common.primitives.Bytes.toArray(mByteValues.build()));
                portableWriter.writeBoolean("__has_ByteValues", true);
            } else {
                portableWriter.writeByteArray("byteValues", new byte[0]);
                portableWriter.writeBoolean("__has_ByteValues", false);
            }
```

If you do:

```java
builder = OptionalListFields.builder().setByteValue(null);
builder.writePortable(...)
```

And then read out from the hazelcat map, the two built messages differ exactly as the bug does.

**Comment by morimekta** [comment]
Fixed in head by fixing the set* method behavior in builders related to isSet.
