### ISSUE TITLE
Add @Generated annotation to generated classes

### ISSUE THREAD

**Issue by zhaakhi** [morimekta/providence#67]
The Generated annotation can be used to mark generated Java code.
https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html

It is used e.g. by error-prone to suppress warnings for generated code, see https://github.com/google/error-prone/issues/463

Behaviour of related tools:
The Thrift compiler annotates with e.g. `@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-05-03")`

AutoValue uses `@Generated("com.google.auto.value.processor.AutoValueProcessor")`

**Comment by morimekta** [comment]
Fixed in HEAD.

Optional param in maven plugin.
