### ISSUE TITLE
Encoding support PVDRPC

### ISSUE THREAD

**Issue by Scrier** [morimekta/providence#87]
So as some items is to be encoded as base64 or other formatting when sent in PVDRPC and I guess apple is a bit a*$l about how things should work. It would be nice to add command line arguments for encoding a call in pvdrpc so it works for both linux and mac (/and eventually windows).

```
SERVER_PARAMS=$(pvd ${INCLUDE} -i json -o binary some_file.SomeCall  <<ENDPARAMS | base64 -w 0
{
}
```

As an example script is not supported on mac as the command works differently there.

**Comment by morimekta** [comment]
https://github.com/morimekta/providence/commit/01edc2f43f3fa5caf2b3444b8544c53404b449fa Makes initial implementation. Has some quirks that needs weeding before really good.
