### ISSUE TITLE
Config: Enable more explicit syntax to update / extend vs assign value

### ISSUE THREAD

**Issue by morimekta** [morimekta/providence#95]
When setting a message (and map?) value there is the option to extend an existing (overridden) value
instead of just assigning it to the given struct. Currently this is dome by removing the `=` sign, which may be confusing to read (and easy to miss).

Suggestion by @stigsb is to use `+=` instead, in the first round to support `+=` in addition and deprecating the "no symbol" syntax, and remove it later on. E.g.

```
config.MyConfig {
  my_field += {
    extended_value = "something"
  }
}
```

Instead of the less explicit:

```
config.MyConfig {
  my_field {
    extended_value = "something"
  }
}
```

Note that the first level (`config.MyConfig {`) will still have no "extend vs replace" symbol, and will *always* extend if it has a parent.

**PS:** This syntax can be used with set / lists too, which will add / append, and maps which will put / replace per key.

**Comment by morimekta** [comment]
**IMHO:** This should *not* allow the user to be able to use a reference (def value) and make multiple levels of extensions, e.g. what this line could suggest:

```
config.MyConfig {
  my_field += reference {
    even_more = "overrides"
  }
}
```

And even this is questionable, though may be acceptable:

```
config.MyConfig {
  my_field += reference
}
```

Note that a lot of info is lost when passing these kind up "updates", e.g. if the object defining the reference unsets a field (field = undefined), that will not affect the merge-like update, as the reference object has already been resolved at this point, resulting in that specific field being not set (but not knowing if an unset operation or no operation is proper).

**Comment by morimekta** [comment]
I am leaning toward a reject on this, citing the possible confusion above.

**Comment by stigsb** [comment]
Seems to me like the benefits do not outweigh the drawbacks then. Consider my proposal withdrawn :)
